/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Auth/Login.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    Register: typeof import('./src/components/Auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
  }
}
